default_context:
  project_name: 'peak-api'
  project_slug: 'peak-api'
  domain_main: 'peakski.com'
  domain_staging: 'stag.peakski.com'
  docker_swarm_stack_name_main: 'peak'
  docker_swarm_stack_name_staging: 'stag-peak'
  secret_key: '99d3b1f01aa639e4a76f4fc281fc834747a543720ba4c8a8648ba755aef9be7f'
  first_superuser: 'admin@peakski.com'
  first_superuser_password: 'password'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.peakski.com", "https://stag.peakski.com", "https://peakski.com", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@peakski.com'
  postgres_password: 'password'
  pgadmin_default_user: 'admin@peakski.com'
  pgadmin_default_user_password: 'password'
  traefik_constraint_tag: 'peakski.com'
  traefik_constraint_tag_staging: 'stag.peakski.com'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:password'
  sentry_dsn: ''
  docker_image_prefix: ''
  docker_image_backend: 'backend'
  docker_image_celeryworker: 'celeryworker'
  docker_image_frontend: 'frontend'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
