"""bunch of changes in db

Revision ID: 2d86eaaf988c
Revises: d4867f3a4c0a
Create Date: 2022-01-30 04:56:50.067722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d86eaaf988c'
down_revision = 'd4867f3a4c0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('from_id', sa.Integer(), nullable=True),
    sa.Column('to_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['from_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['to_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_follower_id'), 'follower', ['id'], unique=False)
    op.add_column('item', sa.Column('link', sa.String(), nullable=True))
    op.add_column('item', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('camera_id', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.drop_index('ix_item_description', table_name='item')
    op.drop_index('ix_item_title', table_name='item')
    op.drop_constraint('item_owner_id_fkey', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'item', 'user', ['camera_id'], ['id'])
    op.drop_column('item', 'description')
    op.drop_column('item', 'title')
    op.drop_column('item', 'owner_id')
    op.add_column('user', sa.Column('first_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(), nullable=True))
    op.add_column('user', sa.Column('profile_pic', sa.String(), nullable=True))
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index('ix_user_full_name', table_name='user')
    op.create_index(op.f('ix_user_first_name'), 'user', ['first_name'], unique=False)
    op.create_index(op.f('ix_user_last_name'), 'user', ['last_name'], unique=False)
    op.drop_column('user', 'full_name')
    op.drop_column('user', 'is_active')
    op.drop_column('user', 'is_superuser')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_superuser', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('user', sa.Column('full_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_user_last_name'), table_name='user')
    op.drop_index(op.f('ix_user_first_name'), table_name='user')
    op.create_index('ix_user_full_name', 'user', ['full_name'], unique=False)
    op.alter_column('user', 'hashed_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('user', 'profile_pic')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'first_name')
    op.add_column('item', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('item', sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key('item_owner_id_fkey', 'item', 'user', ['owner_id'], ['id'])
    op.create_index('ix_item_title', 'item', ['title'], unique=False)
    op.create_index('ix_item_description', 'item', ['description'], unique=False)
    op.drop_column('item', 'timestamp')
    op.drop_column('item', 'camera_id')
    op.drop_column('item', 'user_id')
    op.drop_column('item', 'link')
    op.drop_index(op.f('ix_follower_id'), table_name='follower')
    op.drop_table('follower')
    # ### end Alembic commands ###
