"""Add clips

Revision ID: 58fce20b8730
Revises: 074a7d28546e
Create Date: 2022-01-30 06:00:50.481195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58fce20b8730'
down_revision = '074a7d28546e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
