"""add superuser back

Revision ID: a9eb08364c8c
Revises: 2d86eaaf988c
Create Date: 2022-01-30 05:11:31.981676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9eb08364c8c'
down_revision = '2d86eaaf988c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
